# Generated by Django 4.0.1 on 2022-03-31 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
                ('company', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('payment', models.BooleanField(default=False)),
                ('tax', models.BooleanField(default=False)),
                ('created_date', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EstimatedBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
                ('company', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('client', models.CharField(max_length=100)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.AddField(
            model_name='estimatedbudget',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.project'),
        ),
        migrations.AddField(
            model_name='actualbudget',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.project'),
        ),
    ]
